local cmp_status_ok, tsconfig = pcall(require, 'nvim-treesitter.configs')
if not cmp_status_ok then
	return
end

languages = { 
	-- "astro",
	"bash",
	-- "beancount",
	-- "bibtex",
	-- "c",
	-- "c_sharp",
	-- "clojure",
	-- "cmake",
	-- "comment",
	-- "commonlisp",
	-- "cooklang",
	-- "cpp",
	-- "css",
	-- "cuda",
	-- "d",
	-- "dart",
	-- "devicetree",
	"dockerfile",
	-- "dot",
	-- "eex",
	-- "elixir",
	-- "elm",
	-- "elvish",
	-- "erlang",
	-- "fennel",
	-- "fish",
	-- "foam",
	-- "fortran",
	-- "fusion",
	-- "Godot (gdscript)",
	-- "gleam",
	-- "Glimmer and Ember",
	-- "glsl",
	-- "go",
	-- "Godot Resources (gdresource)",
	-- "gomod",
	-- "gowork",
	"graphql",
	-- "hack",
	-- "haskell",
	-- "hcl",
	-- "heex",
	"help",
	-- "hjson",
	-- "hocon",
	"html",
	"http",
	"java",
	"javascript",
	"jsdoc",
	"json",
	"json5",
	-- "JSON with comments",
	-- "julia",
	-- "kotlin",
	-- "lalrpop",
	-- "latex",
	-- "ledger",
	-- "llvm",
	"lua",
	-- "make",
	-- "markdown",
	-- "ninja",
	-- "nix",
	-- "norg",
	-- "ocaml",
	-- "ocaml_interface",
	-- "ocamllex",
	-- "pascal",
	-- "perl",
	-- "php",
	-- "phpdoc",
	-- "pioasm",
	-- "prisma",
	-- "pug",
	"python",
	-- "ql",
	-- "Tree-sitter query language",
	-- "r",
	-- "rasi",
	"regex",
	-- "rego",
	-- "rst",
	-- "ruby",
	-- "rust",
	"scala",
	-- "scheme",
	"scss",
	-- "slint",
	-- "solidity",
	-- "sparql",
	-- "supercollider",
	-- "surface",
	-- "svelte",
	-- "swift",
	-- "teal",
	-- "tlaplus",
	"todotxt",
	-- "toml",
	-- "tsx",
	-- "turtle",
	"typescript",
	-- "vala",
	-- "verilog",
	"vim",
	"vue",
	-- "wgsl",
	"yaml",
	-- "yang",
	-- "zig",
}


tsconfig.setup({
	ensure_installed = languages,
	sync_install = false,
	ignore_install = { "" }, -- List of parsers to ignore installing
	highlight = {
		enable = true, -- false will disable the whole extension
		disable = { "" }, -- list of language that will be disabled
		additional_vim_regex_highlighting = true,
	},
	indent = { enable = true, disable = { "yaml" } },
	rainbow = {
		enable = true,
		-- disable = { "jsx", "cpp" }, list of languages you want to disable the plugin for
		extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
		max_file_lines = nil, -- Do not enable for files with more than n lines, int
		-- colors = {}, -- table of hex strings
		-- termcolors = {} -- table of colour name strings
	}
})
