" BASE
set nocompatible
set noswapfile
filetype plugin on
set nobackup
set history=1000
set mouse=a

" INTERFACE
syntax enable
set re=0 " Use new regular expression engine
set background=dark
set number relativenumber
set cursorline
set wildmenu
set wildignorecase
set wildignore=\*.git/\*,\*node-modules/\*,\*submodules/\*,*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set wildmode=longest:full,full
set scrolloff=10
set nowrap

" FINDING FILES
set path+=**/*

" INDENTATION BEHAVIOUR
set shiftwidth=4
set tabstop=4
set noexpandtab

" SEARCHING
set incsearch
set ignorecase
set smartcase
set showmatch
set hlsearch
