" BASE
set nocompatible
set noswapfile
filetype plugin on

" INTERFACE
syntax enable
set background=dark
set relativenumber
set cursorline
set wildmenu
set wildignorecase
set wildignore=\*.git/\*
set wildmode=longest:full,full

" FINDING FILES
set path+=**
